name: Deploy Web

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    name: Deploy WebApp to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Set up Flutter
      - name: Flutter Setup
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Checkout repo and get packages
      - name: Checkout WingScore
        uses: actions/checkout@v2

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
