name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # Set up Flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v

      # Checkout repo and get packages
      - uses: actions/checkout@v2
      - run: flutter pub get

      # Analyze, check formatting, and run tests
      - name: Flutter Analyze
        run: flutter analyze

      - name: Ensure Indentation
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Run Flutter Tests
        run: flutter test

  # This should be eventually moved to a "on tag" workflow
  deploy-web:
    name: Deploy WebApp to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v

      # Checkout repo and get packages.
      - uses: actions/checkout@v2
      - run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
